"""migration

Revision ID: d95ad7fb6cdb
Revises: 465cfc43f9f7
Create Date: 2026-05-24 18:20:08.997347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95ad7fb6cdb'
down_revision: Union[str, None] = '465cfc43f9f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_msg_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_msg_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_msg_id'),
    sa.UniqueConstraint('user_id', 'user_msg_id')
    )
    with op.batch_alter_table('messages_to_delete') as batch_op:
        batch_op.alter_column('chat_id',
                              existing_type=sa.INTEGER(),
                              type_=sa.BigInteger(),
                              existing_nullable=False)
    with op.batch_alter_table('tgusers') as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              type_=sa.BigInteger(),
                              existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tgusers') as batch_op:
        batch_op.alter_column('user_id',
                              existing_type=sa.BigInteger(),
                              type_=sa.INTEGER(),
                              existing_nullable=False)
    with op.batch_alter_table('messages_to_delete') as batch_op:
        batch_op.alter_column('chat_id',
                              existing_type=sa.BigInteger(),
                              type_=sa.INTEGER(),
                              existing_nullable=False)
    op.drop_table('message_map')
    # ### end Alembic commands ###
